### ISSUE TITLE
Kodi Matrix 19.x support (python3)

### ISSUE THREAD

**Issue by plaes** [yllar/plugin.video.jupiter.err.ee#1]
When trying to install the addon on Kodi 19 (Matrix), it complains about missing xbmc.python 2.25.0.
https://kodi.wiki/view/Addon.xml#Dependency_versions

Apparently one option to get the addon running with both 2.x and 3.x versions of Python is to get rid of the xbmc.python import: https://forum.kodi.tv/showthread.php?tid=353574&pid=2941339#pid2941339

**[Update]** After dropping the import line: `<import addon="xbmc.python" version="3.0.0"/>`, I got this plugin working also on Kodi 19.

**Comment by yllar** [comment]
Should be fixed in 0.0.3. Thanks
