### ISSUE TITLE
Video playback stalls at 22 seconds

### ISSUE THREAD

**Issue by markouustalu** [yllar/plugin.video.jupiter.err.ee#6]
Jupiter video files are displayed and playback is started, but only plays for 22 seconds. Then it stalls. Live ETV playback works fine.

Kodi: (20.3 (20.3.0) Git:20240110-b3205c8196). Platform: Linux ARM 64-bit

Tested on RPi4 Raspbian and RPi3 Librelec, both act the same.

[kodi.log](https://github.com/yllar/plugin.video.jupiter.err.ee/files/15077043/kodi.log)

**Comment by andrikaro** [comment]
I suspect it is to do something with the inputstreamhelper. I've never worked with Kodi addons before but bumping it to [0.6.1(latest)](https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.6.1) did not yield any different results.

I did notice that it sometimes works, so it seems to be a problem with some specifc DRM content streaming?

Black books or "Raamatupood" works fine for example, other examples as well.

However if it is an issue with inputstreamhelper then further investigation is needed.

Edit:
I'll just point out the error lines in the logs, possibly indicating some problem:
```
2024-04-23 15:33:16.199 T:5229    error <general>: CDVDVideoCodecDRMPRIME::FilterOpen - avfilter_graph_config:  Function not implemented (-38)
...
2024-04-23 15:33:38.828 T:5229    error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: Invalid data found when processing input (-1094995529)
```
